### PR TITLE
Unit tests

### PR DESCRIPTION
**Pull request by whanncar**

### CODE REVIEW

**Comment by yichizhng** [comment]
Make the base fork of the pull request your own copy.

**Comment by whanncar** [comment]
Haha yeah, I was confused but figured it out. The pull request should be
gone?

**Comment by whanncar** [comment]
Oh you closed it. Thanks :D

**Comment by whanncar** [comment]
Oh, also, when are the sets actually due? Midnight or before class? Also
also, how soon will they be graded? I submitted, but I haven't actually
done the merge yet, since I'm waiting on comments from my group.

**Pull request closed without merging**
