### PR TITLE
CS3 HW2: Unit tests

### PR DESCRIPTION
**Pull request by gehpark**
Hi Cindyy review my code that I expertly wrote in class by copying down what was on the board.

### CODE REVIEW

**Comment by xcindylin** [comment]
looks good! yay double nested config (: i think in the hw description it said we're not supposed to change
config_parser.cc so maybe change that back? i don't think it'll affect your units tests!

**Comment by jfarrell468** [comment]
You should fork this repository before cloning it. Otherwise, you won't be able to merge the pull request.

**Comment by gehpark** [comment]
I thought I already forked it before I cloned.. not sure what i did wrong??

**Comment by yichizhng** [comment]
@gehpark - you did, but you want to make the pull request in your forked repo (https://github.com/gehpark/nginx-configparser)
@xcindylin - that was for the part where you're looking for bugs (we want you to find an actual bug, not to introduce a bug into the code and then "find" it) - since you've found one, you should fix it (you will be using this parser for the actual project).

**Pull request closed without merging**
